backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include(("shipments.urls", "shipments"), namespace="shipments")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
]

backend/shipments/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.ShipmentListView.as_view(), name="index"),
    path("<int:pk>/", views.ShipmentDetailView.as_view(), name="detail"),
]

backend/products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(decimal_places=8, max_digits=16)

backend/shipments/models.py
import random

from django.db import models
from model_utils.models import TimeStampedModel, StatusField
from model_utils import Choices


class Shipment(TimeStampedModel):
    STATUS = Choices("pending", "shipped", "delivered")

    shipping_address = models.TextField("Shipping address")
    billing_address = models.TextField("Billing address")
    products_price = models.DecimalField(decimal_places=8, max_digits=16)
    delivery_code = models.IntegerField()
    status = StatusField(choices=STATUS)
    user = models.ForeignKey("users.User", null=True, on_delete=models.SET_NULL)
    shipped_date = models.DateTimeField(null=True, blank=True)
    delivery_date = models.DateTimeField(null=True, blank=True)
    reference_id = models.CharField("Reference ID", max_length=20)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.reference_id = (
                self.user.company.name[:4].upper()
                + str(random.randint(1000, 99999))
                + str(self.user.pk)
                + str(random.randint(1000, 99999))
            )
        super(Shipment, self).save(*args, **kwargs)


class ShipmentDetail(TimeStampedModel):
    shipment = models.ForeignKey(
        "shipments.Shipment", on_delete=models.CASCADE, related_name="shipment_details"
    )
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE)
    quantity = models.IntegerField("Quantity")
    price_per_unit = models.DecimalField(
        "Price per unit", decimal_places=8, max_digits=16
    )
    price = models.DecimalField("Price", decimal_places=8, max_digits=16)

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from model_utils.models import TimeStampedModel


class User(AbstractUser):
    company = models.ForeignKey("users.Company", on_delete=models.CASCADE, null=True)


class Company(TimeStampedModel):
    name = models.CharField(max_length=1025)
    address = models.TextField()
    vat_id = models.CharField(max_length=255)

backend/shipments/views.py
from django.conf import settings
from django.views import generic

from products.models import Product
from shipments.models import Shipment, ShipmentDetail


class ShipmentListView(generic.ListView):
    template_name = "list.html"
    model = Shipment
    context_object_name = "shipments"
    queryset = Shipment.objects.all().select_related("user", "user__company")


class ShipmentDetailView(generic.DetailView):
    template_name = "detail.html"
    model = Shipment
    pk_url_kwarg = "pk"
    queryset = Shipment.objects.all().select_related("user", "user__company")

    def get_context_data(self, **kwargs):
        context = super(ShipmentDetailView, self).get_context_data(**kwargs)
        shipment = self.get_object()
        context["products"] = self.get_products(shipment)
        context["config"] = self.get_config(shipment)
        return context

    def get_products(self, shipment):
        product_ids = ShipmentDetail.objects.filter(shipment=shipment).values_list(
            "product_id", flat=True
        )
        return Product.objects.filter(id__in=product_ids)

    def get_config(self, shipment):
        self.get_products(shipment)
        config = settings.DASHBOARD_SETTINGS.get(
            shipment.status, settings.DASHBOARD_SETTINGS["default"]
        )
        config["product_chart"] = {
            "labels": list(
                shipment.shipment_details.values_list("product__name", flat=True)
            ),
            "data": list(shipment.shipment_details.values_list("quantity", flat=True)),
        }
        return config

backend/shipments/templates/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block main %}
    {% endblock main %}
</body>
</html>

backend/shipments/templates/detail.html
{% extends "base.html" %}
{% load config_tags %}
{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
{% endblock %}

{% block main %}
    <div class="min-h-screen bg-gray-100 space-2">
        <div class="container mx-auto pt-8">
            <div class="grid grid-cols-3 wrap gap-8">
                {% for template_config in config.widgets %}
                    <div class="bg-white rounded-md">
                        {% with template_name=template_config.template|add:".html" %}
                            {% include "widgets/"|add:template_name with title=template_config.title data=config|get_item:template_config.template %}
                        {% endwith %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

backend/shipments/templates/list.html
{% extends "base.html" %}

{% block main %}
    <div class="min-h-screen bg-gray-100 flex justify-center items-center">
        <div>
        <h3 class="text-center mb-6 font-semibold text-2xl">Shipment history</h3>
            <ul role="list" class="space-y-3 w-full">
                {% for shipment in shipments %}
                    <li class="bg-white hover:bg-gray-100 shadow overflow-hidden px-4 py-4 sm:px-6 sm:rounded-md">
                        <a href="{% url "shipments:detail" pk=shipment.id %}">
                            <p class="text-sm font-medium  text-gray-900">Shipment to <span
                                class="text-gray-900 font-semibold">{{ shipment.user.company.name }}</span></p>
                        <div class="flex justify-between mt-1">
                            <p class="text-sm text-gray-500">{{ shipment.created }}</p>
                        <div class="ml-2 flex-shrink-0 flex">
                            {% if shipment.status == "shipped" %}
                                <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">{{ shipment.status }}</p>
                            {% elif shipment.status == "pending" %}
                                <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-orange-100 text-orange-800">{{ shipment.status }}</p>
                            {% else %}
                                <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">{{ shipment.status }}</p>
                            {% endif %}
                        </div>
                        </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>

        </div>
    </div>
{% endblock %}

backend/shipments/templates/widgets/product_chart.html
<div class="p-4 pt-2">
    <div class="border-b border-gray-200 py-2">
        <h4 class="text-base text-gray-500">{{ title }}</h4>
    </div>
    <canvas id="myChart" width="400" height="100"></canvas>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: {{ data.labels|safe  }},
                datasets: [{
                    label: 'Product',
                    data: {{ data.data|safe  }},
                    backgroundColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: "top"
                    },
                    title: {
                        display: true,
                        text: "Products & prices"
                    }
                }
            }
        });
    });

</script>

backend/shipments/templates/widgets/product_prices.html
<div class="p-4 pt-2">
    <div class="border-b border-gray-200 py-2">
        <h4 class="text-base text-gray-500">{{ title }}</h4>
    </div>

    <div>
        <div class="mt-8 flex flex-col">
            <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                    <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-300">
                            <thead class="bg-gray-50">
                            <tr>
                                <th scope="col"
                                    class="whitespace-nowrap py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                                    Product Name
                                </th>
                                <th scope="col"
                                    class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900">
                                    Price
                                </th>
                            </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-200 bg-white">
                            {% for product in products %}
                                <tr>
                                    <td class="whitespace-nowrap px-2 py-2 text-sm font-medium text-gray-900">{{ product.name }}</td>
                                    <td class="whitespace-nowrap px-2 py-2 text-sm font-medium text-gray-900">{{ product.price|floatformat:2 }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/shipments/templates/widgets/shipment_progress.html
<div class="p-4 pt-2">
    <div class="border-b border-gray-200 py-2">
        <h4 class="text-base text-gray-500">{{ title }}</h4>
    </div>
<div>
  <div class="mt-6" aria-hidden="true">
    <div class="bg-gray-200 rounded-full overflow-hidden">
      <div class="h-2 bg-green-600 rounded-full" style="width: 66%"></div>
    </div>
    <div class="hidden sm:grid grid-cols-3 text-sm font-medium text-gray-600 mt-6">
      <div class="text-indigo-600">
          <p>Order Processed</p>
          <p class="text-gray-600">{{ shipment.created|date:"M d, Y" }}</p>
      </div>
      <div class="text-indigo-600">
          <p>Shipped</p>
          <p class="text-gray-600">{{ shipment.shipped_date|date:"M d, Y" }}</p>
      </div>
      <div class="text-center">Delivered</div>
    </div>
  </div>
</div>
</div>


backend/shipments/templates/widgets/shipment_stats.html
<div class="p-4 pt-2">
    <div class="border-b border-gray-200 py-2">
        <h4 class="text-base text-gray-500">{{ title }}</h4>
    </div>
    <div>
        <dl class="mt-5">
                        <div class="px-4 py-5 sm:p-6">
                <dt class="text-base font-normal text-gray-500">Reference Number</dt>
                <dd class="mt-1 flex justify-between items-baseline md:block lg:flex">
                    <div class="flex items-baseline text-2xl font-semibold text-gray-900">
                        {{ shipment.reference_id }}
                    </div>
                </dd>
            </div>
            <div class="px-4 py-5 sm:p-6">
                <dt class="text-base font-normal text-gray-500">Shipment to</dt>
                <dd class="mt-1 flex justify-between items-baseline md:block lg:flex">
                    <div class="flex items-baseline text-2xl font-semibold text-gray-900">
                        {{ shipment.user.company.name }}
                    </div>
                </dd>
            </div>

            <div class="px-4 py-5 sm:p-6">
                <dt class="text-base font-normal text-gray-500">Shipped on</dt>
                <dd class="mt-1 flex justify-between items-baseline md:block lg:flex">
                    <div class="flex items-baseline text-2xl font-semibold text-gray-900">
                        {{ shipment.shipped_date}}
                    </div>

                </dd>
            </div>

            <div class="px-4 py-5 sm:p-6">
                <dt class="text-base font-normal text-gray-500">Status</dt>
                <dd class="mt-1 flex justify-between items-baseline md:block lg:flex">
                    <div class="flex items-baseline text-2xl font-semibold text-gray-900">
                        {{ shipment.status|capfirst }}
                    </div>

                </dd>
            </div>
        </dl>
    </div>
</div>